global:
    scrape_interval: 5s
    external_labels:
        monitor: 'xnat-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
         - targets: ['localhost:9090']

    - job_name: 'containers-monitor'
      static_configs:
         - targets: ['cadvisor:8080']
           
